import { notFound } from "next/navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ArrowLeft, Calendar, Clock, Bot } from "lucide-react"
import Link from "next/link"
import Image from "next/image"
import { SearchBar } from "@/components/search-bar"
import { Footer } from "@/components/footer"
import { ShareButton } from "@/components/share-button"
import { CommentSection } from "@/components/comment-section"
import { getPostBySlug, getAllPosts } from "@/lib/blog"
import ReactMarkdown from "react-markdown"
import { MobileNav } from "@/components/mobile-nav"

export async function generateStaticParams() {
  const posts = await getAllPosts()
  return posts.map((post) => ({
    slug: post.slug,
  }))
}

export default async function BlogPostPage({ params }: { params: { slug: string } }) {
  const post = await getPostBySlug(params.slug)

  if (!post) {
    notFound()
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50 font-mono">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <nav className="flex items-center justify-between">
            <Link href="/" className="flex items-center space-x-2">
              <Bot className="h-8 w-8 text-[#F5A353]" />
              <span className="text-2xl font-bold text-gray-900">AI News Hub</span>
            </Link>
            <div className="hidden md:flex items-center space-x-6">
              <Link href="/blog" className="text-gray-600 hover:text-[#F5A353] transition-colors">
                Blog
              </Link>
              <Link href="/tags" className="text-gray-600 hover:text-[#F5A353] transition-colors">
                Tags
              </Link>
              <Link href="/about" className="text-gray-600 hover:text-[#F5A353] transition-colors">
                About
              </Link>
            </div>
            <div className="flex items-center space-x-2">
              <div className="hidden md:block">
                <SearchBar />
              </div>
              <MobileNav />
            </div>
          </nav>
        </div>
      </header>

      <article className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="mb-8">
          <Link href="/blog">
            <Button variant="ghost" className="mb-6 text-[#F5A353] hover:text-[#E8944A]">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Blog
            </Button>
          </Link>

          <div className="flex items-center gap-2 mb-4">
            <Badge className="bg-[#F5A353] text-white">{post.category}</Badge>
            <span className="text-sm text-gray-500 flex items-center">
              <Calendar className="h-4 w-4 mr-1" />
              {post.date}
            </span>
            <span className="text-sm text-gray-500 flex items-center">
              <Clock className="h-4 w-4 mr-1" />
              {post.readTime} min read
            </span>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6 leading-tight">{post.title}</h1>

          <p className="text-xl text-gray-600 mb-8 leading-relaxed">{post.excerpt}</p>

          {/* Hero Image */}
          {post.heroImage && (
            <div className="mb-8">
              <Image
                src={post.heroImage || "/placeholder.svg"}
                alt={post.title}
                width={800}
                height={400}
                className="w-full h-64 md:h-96 object-cover rounded-lg shadow-lg"
              />
            </div>
          )}

          <div className="flex items-center justify-between border-t border-b py-4 mb-8">
            <div className="flex items-center gap-2">
              <Bot className="h-5 w-5 text-[#F5A353]" />
              <span className="text-sm text-gray-600">Generated by AI</span>
            </div>
            <div className="flex gap-2">
              {post.tags.map((tag) => (
                <Link key={tag} href={`/tags/${tag.toLowerCase()}`}>
                  <Badge variant="outline" className="hover:bg-[#F5A353]/10">
                    {tag}
                  </Badge>
                </Link>
              ))}
            </div>
          </div>
        </div>

        {/* Render the blog post content */}
        <ReactMarkdown className="prose prose-lg max-w-none prose-headings:text-gray-900 prose-p:text-gray-700 prose-a:text-[#F5A353] prose-strong:text-gray-900 prose-code:font-mono prose-pre:font-mono">
          {post.content}
        </ReactMarkdown>

        <div className="mt-12 pt-8 border-t">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Bot className="h-5 w-5 text-[#F5A353]" />
              <span className="text-sm text-gray-600">This article was generated using advanced AI technology</span>
            </div>
            <ShareButton title={post.title} />
          </div>
        </div>

        {/* Comment Section */}
        <CommentSection postSlug={post.slug} />
      </article>

      <Footer />
    </div>
  )
}
